

services:
  server:
    build:
      context: .  # context: . указывает на корневую папку проекта, где находятся и папка client, и папка server, и файл requirements.txt.
      dockerfile: server/Dockerfile  # Указание dockerfile: server/Dockerfile указывает, что нужно использовать Dockerfile из папки server.
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

    networks:
      - my_net

  client:
    build: ./client

    command: python client.py
    depends_on:
      - server
    networks:
      - my_net

networks:
  my_net:
    driver: bridge